/*
 * LeetCode Problem 389: Find the Difference
 * Difficulty: Easy
 *
 * Problem Description:
 * You are given two strings `s` and `t`.
 * 
 * String `t` is generated by randomly shuffling string `s` and then adding
 * one more letter at a random position.
 * 
 * Return the letter that was added to `t`.
 *
 * Examples:
 *
 * Example 1:
 *   Input: s = "abcd", t = "abcde"
 *   Output: "e"
 *   Explanation: 'e' is the letter that was added.
 *
 * Example 2:
 *   Input: s = "", t = "y"
 *   Output: "y"
 *   Explanation: Since s is empty, the only letter in t must be the added one.
 *
 * Constraints:
 *   - 0 <= s.length <= 1000
 *   - t.length == s.length + 1
 *   - s and t consist of lowercase English letters.
 */

char findTheDifference(char* s, char* t) {

    // do a frequency array for s and a frequency array for t, find the element where the frequencies don't match

    if (t == NULL) {
        return '\0';
    }
    
    int freqArrS[26] = {0};
    int freqArrT[26] = {0};

    int lenS = strlen(s);
    int lenT = strlen(t);

    // scan s
    for (int i = 0; i < lenS; i++) {
        freqArrS[s[i] - 'a']++;
    }

    // scan t
    for (int i = 0; i < lenT; i++) {
        freqArrT[t[i] - 'a']++;
    }

    // compare both
    for (int i = 0; i < 26; i++) {
        if (freqArrS[i] != freqArrT[i]) {
            return (char)(i + 'a');
        }
    }
    
    return '\0';
}